### ISSUE TITLE
The results returned by LibSBMLsim need to be mapped to the outputs requested by SED-ML documents

### ISSUE THREAD

**Issue by funasoul** [libsbmlsim/libsbmlsim#13]
The results returned by LibSBMLsim need to be mapped to the outputs requested by SED-ML documents. There's a todo for this in `biosimulators/biosimulators_libsbmlsim/core.py`. Basically, SBML ids and the symbol for time (`urn:sedml:symbol:time`) need to be mapped to specific rows/columns of LibSBMLsim's output data structure and the output needs to be converted to a numpy.array.

**Comment by jonrkarr** [comment]
This is done in the pull request I submitted #15

**Comment by jonrkarr** [comment]
This can be closed.
